// Generated by GraphWalker (http://www.graphwalker.org)
package es.udc.vvs.va.testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "es/udc/vvs/va/testautomation/Vending.graphml")
public interface Vending {

    @Vertex()
    void Ready();

    @Edge()
    void purchase_coke();

    @Edge()
    void insert_coin();

    @Edge()
    void power_up_machine();

    @Vertex()
    void Coke_Available();

    @Vertex()
    void Coffee_Available();

    @Edge()
    void purchase_coffee();
}
