// Generated by GraphWalker (http://www.graphwalker.org)
package es.udc.vvs.va.test.model.testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "es/udc/vvs/va/test/model/testautomation/ContenidoTest.graphml")
public interface ContenidoTest {

    @Vertex()
    void Ready();

    @Edge()
    void e_eliminar_contenido();

    @Edge()
    void e_iniciar_emisora();

    @Edge()
    void e_agregar_contenido();

    @Vertex()
    void v_Emisora_Con_Contenido();

    @Edge()
    void e_buscar_contenido();
}
